#!/usr/bin/env python3
"""Generate the paper's numbers from the modules' own result files.

Nothing in the manuscript is typed by hand. This reads whatever JSON the pipeline has
produced so far and emits `generated.tex`, containing both LaTeX tables and a set of
\\newcommand macros the prose refers to. Two consequences, both deliberate:

  * the paper cannot drift from the code. If a module is re-run, the numbers in the PDF
    change on the next build and no one has to remember to update a table.
  * the paper compiles at any stage. A result file that does not exist yet produces a
    clearly-marked placeholder rather than a LaTeX error, so the manuscript can be written
    and reviewed while experiments are still running.

Usage:  python3 make_tables.py [--drive /path/to/EndoGaussian] [--out generated.tex]
"""
import argparse, json, os, sys

AP = argparse.ArgumentParser()
AP.add_argument('--drive', default=os.environ.get('DRIVE_BASE', ''),
                help='DRIVE_BASE containing module6/, module7/, module8/')
AP.add_argument('--outdir', default=os.path.dirname(os.path.abspath(__file__)))
args = AP.parse_args()

SRC = {
    'm6': f'{args.drive}/module6/module6_metrics.json',
    'm7': f'{args.drive}/module7/module7_comparison.json',
    'm8': f'{args.drive}/module8/module8_hpo.json',
    'm4': f'{args.drive}/module4_combined/module4_metadata.json',
    'rec1': f'{args.drive}/multi_video_summary.json',
    'rec2': f'{args.drive}/videos7_10_summary.json',
}
D = {}
for key, path in SRC.items():
    try:
        D[key] = json.load(open(path))
        print(f'  loaded {key}: {path}')
    except Exception as e:
        D[key] = None
        print(f'  MISSING {key}: {path} ({type(e).__name__}) -- placeholder will be emitted')

# Macros must be defined in the preamble (the abstract uses them); tables must appear in
# the body. They therefore go to separate files -- inputting one file in both places would
# redefine every macro and abort the build.
MACROS, TABLES = [], []
W = TABLES.append
def M(line):
    MACROS.append(line)


def esc(s):
    return str(s).replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')


def placeholder(label, caption, note):
    W(r'\begin{table}[t]\centering')
    W(rf'\caption{{{caption}}}\label{{{label}}}')
    W(r'\begin{tabular}{l}\hline')
    W(rf'\textit{{{note}}}\\ \hline')
    W(r'\end{tabular}\end{table}')
    W('')


def macro(name, value):
    M(rf'\newcommand{{\{name}}}{{{value}}}')


# ── macros the prose uses ────────────────────────────────────────────
M('% ===== auto-generated by make_tables.py -- do not edit =====')
W('% ===== auto-generated by make_tables.py -- do not edit =====')
if D['m4']:
    macro('numVideos', D['m4'].get('n_videos', '??'))
    macro('numAnchors', D['m4'].get('n_anchor', '??'))
    macro('ctxWindow', D['m4'].get('window_size', '??'))
    macro('predSteps', ', '.join(str(k) for k in D['m4'].get('pred_steps', [])))
    macro('numTrainWindows', f"{D['m4'].get('total_train', 0):,}")
    macro('numValWindows', f"{D['m4'].get('total_val', 0):,}")
else:
    PENDING = r'\textit{[pending]}'
    for n, v in (('numVideos', PENDING), ('numAnchors', PENDING), ('ctxWindow', PENDING),
                 ('predSteps', PENDING), ('numTrainWindows', PENDING),
                 ('numValWindows', PENDING)):
        macro(n, v)

if D['m7']:
    r = D['m7']['results']
    best = D['m7']['ranking_by_mpe'][0]
    macro('bestMethod', esc(best))
    macro('bestMPE', f"{r[best]['overall']['mpe']:.4f}")
    if 'Ours — diffusion' in r:
        macro('oursMPE', f"{r['Ours — diffusion']['overall']['mpe']:.4f}")
        macro('oursCD', f"{r['Ours — diffusion']['overall']['cd']:.4f}")
        macro('oursParams', f"{r['Ours — diffusion']['parameters']:,}")
    naive = r.get('Zero motion (naive)', {}).get('overall', {}).get('mpe')
    if naive:
        macro('naiveMPE', f'{naive:.4f}')
else:
    for n in ('bestMethod', 'bestMPE', 'oursMPE', 'oursCD', 'oursParams', 'naiveMPE'):
        macro(n, r'\textit{[pending]}')

# Reconstruction quality, averaged over whatever videos have been reconstructed. Module 2
# writes one entry per workspace across two summary files (videos 1-6 and 7-10).
_rec = {}
for key in ('rec1', 'rec2'):
    if isinstance(D.get(key), dict):
        _rec.update(D[key])
_psnr = [v['psnr'] for v in _rec.values() if isinstance(v, dict) and 'psnr' in v]
_ssim = [v['ssim'] for v in _rec.values() if isinstance(v, dict) and 'ssim' in v]
if _psnr:
    macro('reconPSNR', f'{sum(_psnr) / len(_psnr):.2f}')
    macro('reconSSIM', f'{sum(_ssim) / len(_ssim):.4f}' if _ssim else r'\textit{[pending]}')
    macro('reconVideos', len(_psnr))
else:
    macro('reconPSNR', r'\textit{[pending]}')
    macro('reconSSIM', r'\textit{[pending]}')
    macro('reconVideos', r'\textit{[pending]}')

if D['m6'] and D['m6'].get('hypotheses'):
    macro('calibCorr', f"{D['m6']['hypotheses'].get('spread_error_correlation', float('nan')):.2f}")
    macro('growthExp', f"{D['m6'].get('rollout_growth_exponent', float('nan')):.2f}")
else:
    macro('calibCorr', r'\textit{[pending]}')
    macro('growthExp', r'\textit{[pending]}')
W('')

# ── Table 0: reconstruction quality, ours against published figures ──
W(r'\begin{table}[t]\centering')
W(r'\caption{Reconstruction quality. Published figures are those reported by each method '
  r'on the stereo StereoMIS sequences and are shown for context only: they are obtained on '
  r'different data and with stereo depth supervision, so this is indicative, not a '
  r'controlled comparison.}\label{tab:recon}')
W(r'\begin{tabular}{llrr}\hline')
W(r'Method & Input & PSNR (dB) & SSIM \\ \hline')
W(r'LerPlane~\cite{ruan2023lerplane} & stereo & 29.46 & -- \\')
W(r'EndoGaussian~\cite{liu2024endogaussian} & stereo & 30.25 & -- \\')
W(r'Deform3DGS~\cite{yang2024deform3dgs} & stereo & 30.48 & -- \\ \hline')
if _psnr:
    W(rf"Ours & \textbf{{monocular}} & {sum(_psnr) / len(_psnr):.2f} & "
      rf"{(sum(_ssim) / len(_ssim)) if _ssim else float('nan'):.4f} \\ \hline")
else:
    W(r'Ours & \textbf{monocular} & \textit{[pending]} & \textit{[pending]} \\ \hline')
W(r'\end{tabular}\end{table}')
W('')

# ── Table 1: comparative results ─────────────────────────────────────
if D['m7']:
    res, order = D['m7']['results'], D['m7']['ranking_by_mpe']
    horizons = sorted({int(k) for m in res.values() for k in m['per_horizon']})
    W(r'\begin{table*}[t]\centering')
    W(r'\caption{Comparison against classical estimators and published point-cloud '
      r'prediction methods. All methods are evaluated on the identical held-out windows '
      r'under one protocol. CD is Chamfer Distance (correspondence-free); MPE is Mean '
      r'Point Error, available because Gaussian identity is preserved across frames. '
      r'Lower is better.}\label{tab:comparison}')
    W(r'\begin{tabular}{llrrr' + 'r' * len(horizons) + r'}\hline')
    W(r'Family & Method & Params & CD & MPE & '
      + ' & '.join(rf'MPE $k{{=}}{h}$' for h in horizons) + r'\\ \hline')
    fam_label = {'classical': 'Classical', 'learned': 'Learned', 'ours': 'Ours'}
    for fam in ('classical', 'learned', 'ours'):
        rows = [n for n in order if res[n]['family'] == fam]
        for i, n in enumerate(rows):
            m = res[n]
            par = f"{m['parameters']:,}" if m['parameters'] else '--'
            cells = [f"{m['per_horizon'].get(str(h), m['per_horizon'].get(h, {})).get('mpe', float('nan')):.4f}"
                     for h in horizons]
            W((fam_label[fam] if i == 0 else '') + ' & ' + esc(n) + f' & {par} & '
              + f"{m['overall']['cd']:.4f} & {m['overall']['mpe']:.4f} & "
              + ' & '.join(cells) + r'\\')
        W(r'\hline')
    W(r'\end{tabular}\end{table*}')
    W('')
else:
    placeholder('tab:comparison', 'Comparison against baselines.',
                'Pending: run Module 7 (module7\\_comparison.json not found).')

# ── Table 2: inference cost vs accuracy ──────────────────────────────
if D['m8'] and D['m8']['results'].get('A_inference'):
    g = D['m8']['results']['A_inference']
    knee = D['m8']['results'].get('A_knee', {})
    W(r'\begin{table}[t]\centering')
    W(r'\caption{Inference cost against accuracy. Each prediction costs '
      r'(steps $\times$ samples) network evaluations. The marked row is the cheapest '
      r'setting within 1\% of the best accuracy.}\label{tab:inference}')
    W(r'\begin{tabular}{rrrr}\hline')
    W(r'Steps & Samples & Evaluations & MPE \\ \hline')
    for _, v in sorted(g.items(), key=lambda kv: kv[1]['forward_passes']):
        mark = r'$\star$' if (v['steps'] == knee.get('steps')
                              and v['samples'] == knee.get('samples')) else ''
        W(f"{v['steps']} & {v['samples']} & {v['forward_passes']} & "
          f"{v['mpe']:.4f} {mark} \\\\")
    W(r'\hline\end{tabular}\end{table}')
    W('')
else:
    placeholder('tab:inference', 'Inference cost against accuracy.',
                'Pending: run Module 8 study A.')

# ── Table 3: ablations ───────────────────────────────────────────────
if D['m8'] and D['m8']['results'].get('D_ablations'):
    a = D['m8']['results']['D_ablations']
    W(r'\begin{table}[t]\centering')
    W(rf"\caption{{Ablations on the generative formulation. Screened at "
      rf"{a['screening_epochs']} epochs on {a['screening_fraction']:.0%} of the training "
      rf"windows; the best configurations were re-trained at {a['promoted_epochs']} epochs "
      rf"on the full set.}}\label{{tab:ablation}}")
    W(r'\begin{tabular}{lrr}\hline')
    W(r'Configuration & MPE (screen) & MPE (full) \\ \hline')
    prom = a.get('promoted', {})
    for n, v in sorted(a['screening'].items(), key=lambda kv: kv[1]['mpe']):
        full = f"{prom[n]['mpe']:.4f}" if n in prom else '--'
        W(f"{esc(n)} & {v['mpe']:.4f} & {full} \\\\")
    W(r'\hline\end{tabular}\end{table}')
    W('')
else:
    placeholder('tab:ablation', 'Ablations on the generative formulation.',
                'Pending: run Module 8 study D (RUN\\_D = True).')

# ── Table 4: context length and optimisation sensitivity ─────────────
if D['m8'] and D['m8']['results'].get('B_context'):
    b = D['m8']['results']['B_context']
    W(r'\begin{table}[t]\centering')
    W(r'\caption{Effect of context length, obtained by truncating the observation window.}'
      r'\label{tab:context}')
    W(r'\begin{tabular}{rr}\hline')
    W(r'Context frames $W$ & MPE \\ \hline')
    for w in sorted(b, key=lambda x: int(x)):
        W(f"{w} & {b[w]['mpe']:.4f} \\\\")
    W(r'\hline\end{tabular}\end{table}')
    W('')
else:
    placeholder('tab:context', 'Effect of context length.', 'Pending: run Module 8 study B.')

if D['m8'] and D['m8']['results'].get('C_optimisation'):
    c = D['m8']['results']['C_optimisation']['factors']
    W(r'\begin{table}[t]\centering')
    W(r'\caption{Optimisation sensitivity. Spread is the range in MPE across the values '
      r'tried for each factor, relative to the reference configuration.}'
      r'\label{tab:sensitivity}')
    W(r'\begin{tabular}{lr}\hline')
    W(r'Factor & MPE spread (\%) \\ \hline')
    for lab, d in sorted(c.items(), key=lambda kv: -kv[1]['spread_pct']):
        W(f"{esc(lab)} & {d['spread_pct']:.1f} \\\\")
    W(r'\hline\end{tabular}\end{table}')
    W('')
else:
    placeholder('tab:sensitivity', 'Optimisation sensitivity.',
                'Pending: run Module 8 study C.')

mac_path = os.path.join(args.outdir, 'generated_macros.tex')
tab_path = os.path.join(args.outdir, 'generated_tables.tex')
open(mac_path, 'w').write('\n'.join(MACROS) + '\n')
open(tab_path, 'w').write('\n'.join(TABLES) + '\n')
n_ok = sum(1 for v in D.values() if v)
print(f'\nwrote {mac_path}\n      {tab_path}  ({n_ok}/{len(D)} result files found)')
if n_ok < len(D):
    print('placeholders emitted for the rest; the paper still compiles.')
